import type { AnalyzeResponse, PlanResponse } from "@/types";

/**
 * ISOLATED development fixture for UI testing only.
 *
 * - Used solely when the user explicitly clicks "Load sample data".
 * - Never sent to, mixed with, or presented as a production API response.
 * - The dashboard shows a "SAMPLE DATA" banner whenever this is active.
 */
export function sampleAnalyzeResponse(): AnalyzeResponse {
  return {
    project_title: "Neon Harbor (Sample)",
    run_id: "run-sample-fixture",
    analysis: {
      project_title: "Neon Harbor (Sample)",
      genre: "neo-noir thriller",
      estimated_complexity: "high",
      scenes: [
        {
          scene_number: 1,
          heading: "INT. WAREHOUSE - NIGHT",
          interior_or_exterior: "interior",
          location: "Warehouse",
          time_of_day: "Night",
          characters: ["Mara", "Jack"],
          description: "Mara and Jack argue beside crates of lanterns.",
          production_requirements: ["lantern", "night shoot"],
        },
        {
          scene_number: 2,
          heading: "EXT. PIER 9 - NIGHT",
          interior_or_exterior: "exterior",
          location: "Pier 9",
          time_of_day: "Night",
          characters: ["Mara"],
          description: "A truck chase erupts across the wet pier in the rain.",
          production_requirements: ["truck", "chase", "rain", "night shoot"],
        },
        {
          scene_number: 3,
          heading: "EXT. ROOFTOP - DAY",
          interior_or_exterior: "exterior",
          location: "Rooftop",
          time_of_day: "Day",
          characters: ["Jack"],
          description: "Jack rigs a stunt jump as a helicopter circles.",
          production_requirements: ["helicopter", "stunt", "ZestPop sign"],
        },
        {
          scene_number: 4,
          heading: "INT. DINER - DAY",
          interior_or_exterior: "interior",
          location: "Diner",
          time_of_day: "Day",
          characters: ["Mara", "Jack"],
          description: "Quiet dialogue; a radio plays a commercial song.",
          production_requirements: ["radio song"],
        },
      ],
      characters: ["Mara", "Jack"],
      locations: ["Warehouse", "Pier 9", "Rooftop", "Diner"],
      props: ["Lantern"],
      vehicles: ["truck", "helicopter"],
      brands: ["ZestPop"],
      music: ["radio song"],
      stunts: ["chase", "stunt jump"],
      vfx_requirements: [],
      weather_dependencies: ["rain"],
      time_dependencies: ["night shoot"],
      special_equipment: ["rain rig"],
      permits_or_clearances: ["aerial permit"],
      production_dependencies: ["truck", "chase", "rain"],
      unknowns: [
        "Whether the aerial permit for the Rooftop has been secured is unknown.",
        "Cast availability for the night units is unknown.",
      ],
      initial_concerns: [
        {
          title: "Night pier stunt",
          description: "Chase on a wet pier at night.",
          category: "stunt",
          scene_numbers: [2],
          evidence_level: "explicit",
          recommendation: "Add a safety day.",
        },
      ],
    },
    risks: [
      {
        id: "R-001",
        scene_number: 3,
        affected_scenes: [3],
        category: "permit",
        severity: "critical",
        title: "Rooftop/helicopter access unconfirmed",
        description: "Aerial stunt over a downtown rooftop without confirmed access.",
        why_it_matters: "Without access and an aerial permit the sequence cannot shoot.",
        evidence_items: [
          { kind: "screenplay", text: "helicopter circles above the rooftop" },
          { kind: "inference", text: "Downtown airspace implies permits and closing the block." },
        ],
        recommendation: "Confirm rooftop access and file the aerial permit now.",
        affected_dependencies: ["helicopter", "Rooftop"],
        confidence: "high",
        status: "open",
      },
      {
        id: "R-002",
        scene_number: 2,
        affected_scenes: [2],
        category: "stunt",
        severity: "high",
        title: "Harbor chase needs coordinator",
        description: "Night truck chase on a wet pier in the rain.",
        why_it_matters: "Without a coordinator the shoot day cannot run safely.",
        evidence_items: [
          { kind: "screenplay", text: "A truck chase erupts across the wet pier" },
          {
            kind: "research",
            text: "Pier 9 requires a marine filming permit with 10-day lead.",
            source_title: "Harbor Film Office",
            source_domain: "harborfilm.example",
            source_url: "https://harborfilm.example/permits",
          },
        ],
        recommendation: "Hire a stunt coordinator and add a safety day.",
        affected_dependencies: ["truck", "chase", "rain"],
        confidence: "high",
        status: "open",
      },
      {
        id: "R-003",
        affected_scenes: [1, 2],
        category: "schedule",
        severity: "medium",
        title: "Scattered night exteriors",
        description: "Night work split across warehouse and pier units.",
        why_it_matters: "Split night units inflate overtime and turnaround risk.",
        evidence_items: [{ kind: "inference", text: "Two night locations imply split units." }],
        recommendation: "Consolidate night work into consecutive nights.",
        affected_dependencies: ["night shoot"],
        confidence: "medium",
        status: "open",
      },
      {
        id: "R-004",
        category: "brand",
        severity: "low",
        title: "Visible soft-drink signage",
        description: "ZestPop sign visible on the rooftop.",
        why_it_matters: "Uncleared marks must be removed in post.",
        evidence_items: [{ kind: "screenplay", text: "ZestPop sign" }],
        recommendation: "Clear the mark or replace with a fictional brand.",
        affected_dependencies: ["ZestPop"],
        confidence: "low",
        status: "open",
      },
    ],
    dependencies: [
      {
        id: "D-001",
        source_risk_id: "R-001",
        target_risk_id: "R-002",
        relationship: "blocks",
        impact: "Aerial unit holds while rooftop access clears.",
      },
    ],
    recommendations: [
      {
        id: "REC-001",
        priority: 1,
        title: "Confirm rooftop access and aerial permit",
        description: "Call the film office; file before locking Scene 3.",
        addresses_risk_ids: ["R-001"],
        expected_impact: "Removes the critical blocker.",
        action_type: "obtain_permit",
      },
      {
        id: "REC-002",
        priority: 2,
        title: "Plan the harbor stunt",
        description: "Coordinator plus rehearsal day for Scene 2.",
        addresses_risk_ids: ["R-002"],
        expected_impact: "Removes the high stunt penalty.",
        action_type: "plan_stunt",
      },
    ],
    research: [
      {
        topic: "Pier 9 filming permits",
        provider: "parallel",
        status: "complete",
        summary: "1 source returned for harbor permits.",
        sources: [
          {
            title: "Harbor Film Office",
            domain: "harborfilm.example",
            url: "https://harborfilm.example/permits",
            excerpt: "Marine filming permits require a 10-day lead.",
          },
        ],
      },
      {
        topic: "Rooftop airspace rules",
        provider: "parallel",
        status: "error",
        summary: "Provider timed out.",
        sources: [],
      },
    ],
    readiness: {
      score: 77.5,
      status: "AT RISK",
      critical_count: 1,
      high_count: 1,
      medium_count: 1,
      low_count: 1,
      total_risks: 4,
      blockers: ["R-001", "R-002"],
      methodology: "Sample fixture methodology.",
      penalty_breakdown: [
        { severity: "critical", count: 1, weight: 15, penalty: 15 },
        { severity: "high", count: 1, weight: 5, penalty: 5 },
        { severity: "medium", count: 1, weight: 2, penalty: 2 },
        { severity: "low", count: 1, weight: 0.5, penalty: 0.5 },
      ],
    },
    research_notes: ["Sample fixture research notes."],
    readiness_score: 77.5,
    risk_counts: { critical: 1, high: 1, medium: 1, low: 1 },
    analysis_source: "fixture",
  };
}

export function samplePlanResponse(): PlanResponse {
  return {
    project_title: "Neon Harbor (Sample)",
    run_id: "run-sample-fixture",
    affected_risk_ids: ["R-001", "R-002"],
    projected_readiness: {
      score: 97.5,
      status: "READY",
      critical_count: 0,
      high_count: 0,
      medium_count: 1,
      low_count: 1,
      total_risks: 4,
      blockers: [],
    },
    fix_plan: {
      actions: [
        {
          id: "ACT-001",
          recommendation_id: "REC-001",
          title: "Confirm rooftop access and aerial permit",
          affected_scenes: [3],
          affected_risk_ids: ["R-001"],
          expected_risk_reduction: 15.0,
          schedule_impact: "File this week; hold Scene 3 dates tentative.",
        },
        {
          id: "ACT-002",
          recommendation_id: "REC-002",
          title: "Plan the harbor stunt",
          affected_scenes: [2],
          affected_risk_ids: ["R-002"],
          expected_risk_reduction: 5.0,
          schedule_impact: "Add one rehearsal day before the pier unit.",
        },
      ],
      affected_risk_ids: ["R-001", "R-002"],
      projected_readiness: {
        score: 97.5,
        status: "READY",
        critical_count: 0,
        high_count: 0,
        medium_count: 1,
        low_count: 1,
        total_risks: 4,
        blockers: [],
      },
      remaining_blockers: [],
      schedule_impact: "2 actions covering 2 risks.",
      revised_plan: "Execute both actions, then re-run analysis to confirm.",
    },
  };
}
